name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: make-depend
      run: make depend
    - name: Build
      run: make build
    - name: Tidy
      run: go mod tidy

    - name: Test
      run: make test

    - name: Release
    uses: softprops/action-gh-release@v1
    with:
      files: |
        build/wstunnel-linux-amd64.tgz
        build/wstunnel-windows-amd64.zip

    # - name: Upload assets build
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: wstunnel
    #     path: build/*

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.RELEASER_GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false


